// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV9dJI1RcMXLngQ7ZUbAj6LC3V-ZCuksA',
    appId: '1:954967254985:web:5b61a55a3566415d24ea18',
    messagingSenderId: '954967254985',
    projectId: 'the-last-number',
    authDomain: 'the-last-number.firebaseapp.com',
    storageBucket: 'the-last-number.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4ZgsVhLELZE7YCPvkZwdBSLrYey2GbM',
    appId: '1:954967254985:android:7874e501f844628924ea18',
    messagingSenderId: '954967254985',
    projectId: 'the-last-number',
    storageBucket: 'the-last-number.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDCFgeVEw-jVVxc5OCRaXIBh4XanzRpss',
    appId: '1:954967254985:ios:cdc6d21ee156181524ea18',
    messagingSenderId: '954967254985',
    projectId: 'the-last-number',
    storageBucket: 'the-last-number.firebasestorage.app',
    iosClientId: '954967254985-g8akq9qb7uias6rv241dnq7dfmsv4bef.apps.googleusercontent.com',
    iosBundleId: 'com.example.ekSauEk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDCFgeVEw-jVVxc5OCRaXIBh4XanzRpss',
    appId: '1:954967254985:ios:cdc6d21ee156181524ea18',
    messagingSenderId: '954967254985',
    projectId: 'the-last-number',
    storageBucket: 'the-last-number.firebasestorage.app',
    iosClientId: '954967254985-g8akq9qb7uias6rv241dnq7dfmsv4bef.apps.googleusercontent.com',
    iosBundleId: 'com.example.ekSauEk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV9dJI1RcMXLngQ7ZUbAj6LC3V-ZCuksA',
    appId: '1:954967254985:web:3d8705237f4f90d924ea18',
    messagingSenderId: '954967254985',
    projectId: 'the-last-number',
    authDomain: 'the-last-number.firebaseapp.com',
    storageBucket: 'the-last-number.firebasestorage.app',
  );
}
